# .github/workflows/create_pr_with_gh.yml

name: Create Pull Request using GitHub CLI

on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: 'The branch to create the PR from'
        required: true
        default: 'develop'
        type: string
      target_branch:
        description: 'The branch to merge into'
        default: 'main'
        type: string

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.10.1
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: Auto Pull Request
          title: Your desired title
          body: Auto-created Pull Request
          branch: ${{ github.event.inputs.source_branch }}
          base: main
          labels: |
            gitstream-auto-merge
