# .github/workflows/create_pr_with_gh.yml

name: Create Pull Request using GitHub CLI

on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: 'The branch to create the PR from'
        required: true
        default: 'develop'
        type: string
      target_branch:
        description: 'The branch to merge into'
        default: 'main'
        type: string

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up GitHub CLI
      - name: Set up GitHub CLI
        run: |
          sudo apt-get install gh
          gh auth login --with-token <<< ${{ secrets.GH_TOKEN }}

      # Step 3: Configure Git
      - name: Set up Git
        run: |
          git config user.name "github-actions-bot"
          git config user.email "github-actions-bot@users.noreply.github.com"

      # Step 4: Make changes to the repository (e.g., update a file)
      - name: Make changes
        run: |
          echo "Automated update on $(date)" >> automated_changes.txt
          git add automated_changes.txt

      # Step 5: Commit the changes
      - name: Commit changes
        run: |
          git commit -m "Automated update: $(date)" || echo "No changes to commit"

      # Step 6: Push the changes to a new branch
      - name: Push changes
        run: |
          git checkout -b automated-update-${{ github.run_id }}
          git push origin automated-update-${{ github.run_id }}

      # Step 7: Create a pull request using GitHub CLI
      - name: Create Pull Request
        run: |
          gh pr create --title "Automated Update" \
            --body "This pull request was automatically generated by a GitHub Action." \
            --head automated-update-${{ github.run_id }} \
            --base ${{ github.event.inputs.target_branch }} \
            --label "gitstream-auto-merge"
